let num = 5
num;
num;
num;
num;
num;
num;
num;
num;



try {

    num;
    num;
    throw "somethings wrong!"
    num;
    console.log("Hello Everyone!")
    
} catch (error) {

    console.log("Error happened: ", error)
    
}

console.log("asdfasdf")

num;
num;
num;
num;
num;
num;